name: kyc_verification
description: "A reusable KYC verification Flutter package"
version: 0.0.2

homepage: https://github.com/gayathribalraj/kyc_package
repository: https://github.com/gayathribalraj/kyc_package

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.9.0
  encrypt: ^5.0.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_otp_text_field: ^1.5.1+1
  pretty_dio_logger: ^1.4.0
  reactive_forms: ^18.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
 # Example for asset usage (uncomment if needed)
  assets:
    - assets/kyc_behavior.png


